=== DiogoFerreira99/DAW2020/T3/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT pr (metadata , workteam , abstract , deliverables) >

<!ELEMENT metadata (keyname, title, subtitle? ,begindate, enddate, supervisor) >

<!ELEMENT keyname (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begindate (#PCDATA) >
<!ELEMENT enddate (#PCDATA) >

<!ELEMENT supervisor (name, url?) >

<!ELEMENT name (#PCDATA) >
<!ELEMENT url (#PCDATA) >

<!ELEMENT link (text, url) >

<!ELEMENT workteam (membro+) >

<!ELEMENT membro (name, id,email, link?) >

<!ELEMENT id (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!ELEMENT abstract (paragraph+) >

<!ELEMENT paragraph (#PCDATA | italic | bold | under | link)* >

<!ELEMENT italic (#PCDATA) >
<!ELEMENT bold (#PCDATA) >
<!ELEMENT under (#PCDATA) >

<!ELEMENT deliverables (link*) >

<!ELEMENT text (#PCDATA) >

=== DiogoFerreira99/DAW2020/T3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "pr.dtd">
<pr>
    <metadata>
        <keyname></keyname>
        <title>Trabalho de casa 3: desenvolvimento de um website com base num dataset de sitios de interesse arqueológico</title>
        <begindate>21 de outubro de 2020 </begindate>
        <enddate></enddate>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <url></url>
        </supervisor>
    </metadata>
    <workteam>
        <membro>
            <name>Diogo Araújo Ferreira</name>
            <id>pg42824</id>
            <email>pg42824@alunos.uminho.pt</email>
        </membro>
    </workteam>
    <abstract>
        <paragraph>
            Desenvolvimento de um dtd para este dataset:
            atendendo ao formato  irregular do dataset apresentado a tag elem permite 
            qualquer tag no seu interior, pois a única outra opção que obrigaria à existência de 
            qualquer ordem implacava o resgisto de todas as comutações das tags já existentes no 
            dataset, algo muito extenso. Tirando os campos que representam números , códigos de identificação,
            lugares, freguesias e concelhos, todos os outros campos são compostos por PCDATA ou
            LIGA, que eu suponho que fossem ligações a documentos externos.
        </paragraph>
        <paragraph>
            Desenvolvimento do índice:
            foi gerado um índice ordenado alfabeticamente tal como foi efetuado na aula, mas 
            mais uma vez devido à irregularidade dos dados e à existencia de acentos ,tive que 
            especificar a língua do campo utilizado na ordenação pois a entrada com identificação 
            Àzere aparecia no fim do índice. 
            A especificação da língua resolveu também outro problema na ordenação relacionado
            com a existencia de espaços entre a tag IDENTI e o nome do local, que tinha como 
            efeito o aparecimento no final do índice das entradas que não apresentavam tal 
            espaço.
        </paragraph>
        <paragraph>
            As referências para as páginas dos locais e de volta ao índice foram 
            geradas da mesma maneira que na aula.
        </paragraph>
        <paragraph>
            Desenvolvimento das páginas dos locais:
            a única diferença entre a geração destas páginas e das páginas que 
            gerámos no exemplo das aulas, é que neste caso tive de especificar uma 
            ordem para a aplicação das templates. Caso tal não fosse feito devido à 
            não existencia de uma ordem estabelecida na apresentação dos parametros,
            estes apareceriam em diferentes locais para páginas diferentes. Todas as 
            tags liga foram simplesmente ignoradas.
        </paragraph>
    </abstract>
    <deliverables>
        <link>
            <text>DTD correspondente ao formato xml do dataset</text>
            <url>arq.dtd</url>
        </link>
        <link>
            <text>Ficheiro gerador das páginas HTML</text>
            <url>arq_web_2.xsl</url>
        </link>
        <link>
            <text>Ficheiro HTML do índice do website</text>
            <url>site/index.html</url>
        </link>
        <link>
            <text>Ficheiro css aplicado na geração das páginas HTML</text>
            <url>arq.css</url>
        </link>     
    </deliverables>
</pr>

=== DiogoFerreira99/DAW2020/T2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "pr.dtd">
<pr>
    <metadata>
        <keyname></keyname>
        <title>Trabalho de casa 2: desenvolvimento de uma dtd para pr's</title>
        <begindate>21 de outubro de 2020 </begindate>
        <enddate></enddate>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <url></url>
        </supervisor>
    </metadata>
    <workteam>
        <membro>
            <name>Diogo Araújo Ferreira</name>
            <id>pg42824</id>
            <email>pg42824@alunos.uminho.pt</email>
        </membro>
    </workteam>
    <abstract>
        <paragraph>
            Atendendo ao formato que nos foi apresentado na aula e ao que o professor
            sugeriu temos a divisão do documento em quatro partes, metadados, equipa de trabalho,
            abstrato e documentos a entregar.
        </paragraph>
        <paragraph>
            Nos metadados tal como indicado temos o keyname, título, subtítulo (sendo 
            este definido como opcional) e o supervisor. O supervisor foi definido com os
            campos nome e url sendo este último opcional.
        </paragraph>
        <paragraph>
            A equipa de trabalho defini como um lista com um ou mais membros. Cada
            membro tem um nome, um id, um email e tem como campo opcional um 
            link que é composto pelo texto que queremos apresentar e o url.
        </paragraph>
        <paragraph>
            Estabeleci que o abstrato é uma lista com um ou mais paragrafos. 
            Por sua vez cada paragrafo é um conjunto com 0  ou mais elementos de #PCDATA, <under>sublinados</under>,
            <italic>itálico</italic>, <bold>bold</bold> e links.
        </paragraph>
        <paragraph>
            Por útimo os documentos a entregar são uma lista com 0 ou mais 
            elementos em que cada elemento tem um nome e url associados.
        </paragraph>
    </abstract>
    <deliverables>
        <document>
            <name>DTD correspondente ao formato xml aqui apresentado</name>
            <url>pr.dtd</url>
        </document>
    </deliverables>
</pr>
